### ISSUE TITLE
FixMath library is missing

### ISSUE THREAD

**Issue by HomineLudens** [pokitto/PokittoIO#1]
It seems like fix math library has not been included in this repository.

**Comment by Pharap** [comment]
I think it makes sense to not bundle other libraries with this library unless they're Pokitto specific.

I think it would make more sense to put general libraries (like fixmath) in PlatformIO's lib folder instead of trying to bundle them with the PokittoLib.

**Comment by pokitto** [comment]
I'm making an exeption with FixMath. I think it should be in the core package
